ccflags-y += -Idrivers/media/platform/msm/camera_v2-rosy
ccflags-y += -Idrivers/media/platform/msm/camera_v2-rosy/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-rosy/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-rosy/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
obj-y += msm_eeprom_insensor_ov13850.o
