ccflags-y += -Idrivers/media/platform/msm/camera_v2-rosy
ccflags-y += -Idrivers/media/platform/msm/camera_v2-rosy/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2-rosy/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-rosy/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-rosy/msm_buf_mgr/
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
