ccflags-y += -Idrivers/media/platform/msm/camera_v2-rosy
ccflags-y += -Idrivers/media/platform/msm/camera_v2-rosy/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-rosy/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_ir_led.o
