#!/usr/bin/env dash
# shellcheck source=/dev/null
#
# Copyright (C) 2018 Raphielscape LLC.
#
# Licensed under the Raphielscape Public License, Version 1.0 (the "License");
# you may not use this file except in compliance with the License.
#
# Telegram command container

TELEGRAM=$KERNEL_DIR/telegram

# Caster configurations
MAINGROUP_ID="-1001124797505"
BUILDSCAPERER_ID="-1001395793012"
DEBUG_ID="-1001242182605"

# Graphics Interchange Format Assets
Start_Asset="CAADBQADBgADcHz3IpDKOqKNQ1ReAg"
Stop_Asset="https://i.imgur.com/Q6nllGX.gif"
Jump_Asset="https://media.giphy.com/media/l41lI4bYmcsPJX9Go/giphy.gif"

# GIF Stuff
tg_build_sendsticker() {
    curl -s -X POST "https://api.telegram.org/bot$BOT_API_KEY/SendSticker" \
    -d sticker="${Start_Asset}" \
    -d chat_id=${BUILDSCAPERER_ID} >> /dev/null
}

tg_buildmain_sendgif() {
    curl -s -X POST "https://api.telegram.org/bot$BOT_API_KEY/SendAnimation" \
    -d animation="${Jump_Asset}" \
    -d chat_id=${MAINGROUP_ID} >> /dev/null
}

# Interruption Happen, report with GIF
tg_intgif() {
    curl -s -X POST "https://api.telegram.org/bot$BOT_API_KEY/SendAnimation" \
    -d animation="${Stop_Asset}" \
    -d chat_id=${BUILDSCAPERER_ID} >> /dev/null
}

tg_intgifmain() {
    curl -s -X POST "https://api.telegram.org/bot$BOT_API_KEY/SendAnimation" \
    -d animation="${Stop_Asset}" \
    -d chat_id=${MAINGROUP_ID} >> /dev/ -t null
}

tg_sendchanges() {
    curl -s -X POST "https://api.telegram.org/bot$BOT_API_KEY/sendMessage" \
    -F text="$(./changelog.sh)" \
    -d chat_id=${MAINGROUP_ID} >> /dev/ -t null
}

tg_changelogs() {
    curl -s -X POST "https://api.telegram.org/bot$BOT_API_KEY/sendMessage" \
    -F text="$(./changelog.sh)" \
    -d chat_id=${BUILDSCAPERER_ID} >> /dev/ -t null
}

# Push to Group
push() {
    "${TELEGRAM}" -f "Nano_Kernel-rosy.zip" \
    -c ${BUILDSCAPERER_ID} -t $BOT_API_KEY
    tg_sendchanges
}

# Push to Channel
push() {
    "${TELEGRAM}" -f "Nano_Kernel-rosy.zip" \
    -c ${MAINGROUP_ID} -t $BOT_API_KEY
    tg_changelogs
    tg_build_sendsticker
}

# sendcast to group
tg_sendinfo() {
    "${TELEGRAM}" -c ${MAINGROUP_ID} -H \
    "$(
		for POST in "${@}"; do
			echo "${POST}"
		done
    )" \
    -t $BOT_API_KEY
}

# sendcast to channel
tg_channelcast() {
    "${TELEGRAM}" -c ${BUILDSCAPERER_ID} -H \
    "$(
		for POST in "${@}"; do
			echo "${POST}"
		done
    )" \
    -t $BOT_API_KEY
}

# Debugcasting
tg_debugcast() {
    "${TELEGRAM}" -c ${DEBUG_ID} -H \
    "$(
		for POST in "${@}"; do
			echo "${POST}"
		done
    )" \
    -t $BOT_API_KEY
}

kickstart_pub() {

    tg_sendinfo "<b>Making New public build</b>" \
    " " \
    "<b>Device:</b> <i>Rosy</i>" \
    "<b>Branch:</b> <code>Pie</code>" \
    " " \
    "<b>Started on</b> <code>Nano-CI</code>" \
    " " \
    "<b>Under:</b> <code>Codeship-server</code>" \
    " " \
    "<b>Repository:</b> https://github.com/shreejoy/Nano_rosy"
}
kickstart_priv() {

    tg_debugcast "Making New private Build" \
    "<b>Device:</b> Rosy" \
    "<b>Branch:</b> <code>${PARSE_BRANCH}</code>" \
    " " \
    "Started on <code>$(whoami)</code>" \
    " " \
    "Under <code>$(hostname)</code>" \
    " " \
    "Commit Point <code>${COMMIT_POINT}</code>" \

    tg_debugcast "This ${COMPILER_USED} build will not producing any binaries" \
                "This is internal build"
}

