ccflags-y += -Idrivers/media/platform/msm/camera_v2-rosy
ccflags-y += -Idrivers/media/platform/msm/camera_v2-rosy/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-rosy/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-rosy/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
